### PR TITLE
Create 2014-10-18-RamallahMapathon

### PR DESCRIPTION
**Pull request by Ecolevas**

### CODE REVIEW

**Comment by d3netxer** [comment]
@Ecolevas were both posts _posts/news/2014-08-27-NACCHO.md and _posts/news/2014-12-17-digitalgov.md deleted? They both shared the same link, obviously an error. How about delete just _posts/news/2014-08-27-NACCHO.md and keep _posts/news/2014-12-17-digitalgov.md?

**Comment by d3netxer** [comment]
I accepted the merge then re-added 2014-12-17-digitalgov.md . You can delete again if there was another reason to.

**Comment by Ecolevas** [comment]
So these three appear to be identical--I kept 2014-03-12-fastcoexist.md but of course it doesn't matter which one we keep (unless there's another issue I'm unaware of)

2014-08-27-NACCHO.md

2014-12-17-digitalgov.md

2014-03-12-fastcoexist.md

**Comment by bensonwilder** [comment]
Electra, just wanted to say I really appreciate all this help. Keep on
trucking!

**Comment by mikelmaron** [comment]
those were all mislinked to digitalgov


http://nacchopreparedness.org/?p=2904

http://www.fastcoexist.com/3027507/the-us-state-department-wants-you-to-go-to-your-computer-and-help-it-make-maps

**Pull request merged**
